spring.application.name=eldernest-backend
server.port=8080
server.servlet.context-path=/
spring.profiles.active=dev
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration